defaults:
  - _self_
  - train: 1_5b
  # - train: train_mixtral_1.8b

experiment:
  exp_name: train_qwen_2.5_1.5b
  exp_dir: ./outputs # outputs ## log、checkpoints output path
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_gpt.py
  cmds:
    before_start: |
      if [ -n "$CONDA_SH" ]; then
        source "$CONDA_SH"
      else
        source "$HOME/miniconda3/etc/profile.d/conda.sh"
      fi
      if [ -n "$FLAGSCALE_TRAIN_ENV" ]; then
        conda activate "$FLAGSCALE_TRAIN_ENV"
      else
        conda activate flagscale-train
      fi
  runner:
    backend: torchrun
    nnodes: 1
    nproc_per_node: 2
  envs:
    CUDA_VISIBLE_DEVICES: "0,1"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    NCCL_SOCKET_IFNAME: lo
    NCCL_IB_DISABLE: 1
    NCCL_IB_CUDA_SUPPORT: 1
    NCCL_IB_GID_INDEX: 0
    NCCL_DEBUG: INFO
    OMP_NUM_THREADS: 4
    GLOO_SOCKET_IFNAME: lo
    NCCL_IB_HCA: mlx5_2,mlx5_5
    WANDB_MODE: offline # make sure if needed afterwards

action: run
